import {
  LuArrowRight,
  LuArrowUp,
  LuArrowUpRight,
  LuBadgeCheck,
  LuBookOpen,
  LuBot,
  LuBrain,
  LuBoxes,
  LuBriefcase,
  LuCalendar,
  LuChartColumn,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuCircuitBoard,
  LuClock,
  LuCode,
  LuCompass,
  LuCpu,
  LuExternalLink,
  LuGlobe,
  LuGraduationCap,
  LuHand,
  LuHandshake,
  LuHeartHandshake,
  LuLaptop,
  LuLayers,
  LuLeaf,
  LuLightbulb,
  LuLoaderCircle,
  LuMail,
  LuMapPin,
  LuMenu,
  LuMessageCircle,
  LuMinus,
  LuMonitorSmartphone,
  LuMoon,
  LuPackage,
  LuPartyPopper,
  LuPhone,
  LuPlay,
  LuPlus,
  LuPrinter,
  LuQuote,
  LuRocket,
  LuSchool,
  LuSearch,
  LuSend,
  LuSettings,
  LuShieldCheck,
  LuSparkles,
  LuStar,
  LuSun,
  LuTag,
  LuTarget,
  LuTriangleAlert,
  LuUsers,
  LuWifi,
  LuWrench,
  LuX,
  LuZap,
} from 'react-icons/lu'
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaWhatsapp, FaXTwitter } from 'react-icons/fa6'

/** Named icon registry so data files can stay plain, serialisable JS. */
export const Icon = {
  arrowRight: LuArrowRight,
  arrowUp: LuArrowUp,
  arrowUpRight: LuArrowUpRight,
  badge: LuBadgeCheck,
  book: LuBookOpen,
  boxes: LuBoxes,
  box: LuPackage,
  brain: LuBrain,
  briefcase: LuBriefcase,
  calendar: LuCalendar,
  chart: LuChartColumn,
  check: LuCheck,
  chevronDown: LuChevronDown,
  chevronLeft: LuChevronLeft,
  chevronRight: LuChevronRight,
  chip: LuCpu,
  circuit: LuCircuitBoard,
  clock: LuClock,
  code: LuCode,
  compass: LuCompass,
  external: LuExternalLink,
  gear: LuSettings,
  globe: LuGlobe,
  graduation: LuGraduationCap,
  hands: LuHand,
  handshake: LuHandshake,
  heart: LuHeartHandshake,
  laptop: LuLaptop,
  layers: LuLayers,
  leaf: LuLeaf,
  lightbulb: LuLightbulb,
  mail: LuMail,
  mapPin: LuMapPin,
  menu: LuMenu,
  message: LuMessageCircle,
  minus: LuMinus,
  moon: LuMoon,
  party: LuPartyPopper,
  phone: LuPhone,
  play: LuPlay,
  plus: LuPlus,
  printer: LuPrinter,
  quote: LuQuote,
  robot: LuBot,
  rocket: LuRocket,
  school: LuSchool,
  search: LuSearch,
  send: LuSend,
  shield: LuShieldCheck,
  spinner: LuLoaderCircle,
  sparkle: LuSparkles,
  star: LuStar,
  sun: LuSun,
  tag: LuTag,
  target: LuTarget,
  tools: LuWrench,
  users: LuUsers,
  devices: LuMonitorSmartphone,
  warning: LuTriangleAlert,
  wifi: LuWifi,
  x: LuX,
  zap: LuZap,
}

export const SocialIcon = {
  twitter: FaXTwitter,
  facebook: FaFacebookF,
  instagram: FaInstagram,
  linkedin: FaLinkedinIn,
  whatsapp: FaWhatsapp,
}

export const getIcon = (name, fallback = LuSparkles) => Icon[name] ?? fallback
